name = "r2lsr" # The name of you worker
main = "src/index.ts"
compatibility_date = "2024-03-04"

account_id = "YOUR_ID" # You Cloudflare account id
workers_dev = true

[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'YOU_BUCKET_NAME'
preview_bucket_name = 'YOU_DEV_BUCKET_NAME'

[placement]
mode = "smart"